on: [push, pull_request]
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

name: Test

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, gd
      - name: PhpStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon
      - name: Unit tests via PHPUnit
        run: ./vendor/bin/phpunit ./tests/
